import type { WorkingRow } from "../src/lib/domain/types";

export function makeRow(overrides: Partial<WorkingRow> = {}): WorkingRow {
  return {
    id: "STR001|SKU001",
    selected: false,
    storeId: "STR001",
    storeName: "Sport Store 1",
    routeId: "R01",
    deliveryDay: "Monday",
    category: "Apparel",
    skuId: "SKU001",
    styleColorSize: "STY001-Black-M",
    productDescription: "T-Shirt Black M",
    systemRecommendedQty: 0,
    finalQty: 0,
    stockOnHand: 2,
    inTransitQty: 0,
    averageDailySales: 2,
    forecastNext7: 14,
    forecastNext14: 28,
    daysOfCover: 1,
    projectedDaysOfCover: 1,
    daysToDelivery: 4,
    packMultiple: 6,
    dcTotalStock: 200,
    dcFreeStock: 120,
    dcFreeStockOriginal: 120,
    revenueAtRisk: 0,
    marginAtRisk: 0,
    expectedRecoveredRevenue: 0,
    expectedRecoveredMargin: 0,
    forecastConfidence: 0.8,
    promoFlag: false,
    promoUpliftPct: 0,
    seasonalIndex: 1,
    riskLevel: "Low",
    reasonCode: "No replenishment needed",
    constraintStatus: "Valid",
    constraintMessages: [],
    comment: "",
    manualOverride: false,
    dataIssue: false,
    dataIssueSeverity: "",
    dataIssueDescription: "",
    ranged: true,
    replenishable: true,
    storeSkuCapacityUnits: 60,
    softCategoryCapacityUnits: 500,
    hardCategoryCapacityUnits: 600,
    receivingCapacityUnits: 300,
    unitCost: 20,
    sellingPrice: 50,
    grossMarginPct: 0.6,
    minPresentationQty: 3,
    targetCoverDays: 14,
    minCoverDays: 5,
    maxCoverDays: 18,
    serviceLevelTarget: 0.92,
    storeSkuPriority: 0.9,
    lifecycleStatus: "Active",
    ...overrides
  };
}
